### ISSUE TITLE
Getting in touch

### ISSUE THREAD

**Issue by skryl** [dabear/miaomiao-client-swift#11]
Hey Bjorn, I'm pretty far along with building a Swift library for interacting with the Freestyle Libre. All the low level NFC work is done but I'm struggling a bit with processing of the raw glucose values coming from the sensor. Maybe you can help me out with a few questions?

**Comment by dabear** [comment]
Hi. On iOS IT is not possible to replicate the result from the abbot algoritm without using online service such as my libreoopweb or glukose.space. @upetersen has sone most of the mapping of the sensor data to swift data structures. See the sensordata class. For l2 and encrypted US sensors you must always use the webservice for each nfc readout. for l1 you can work on the raw data as you want as there is No encryption. You can also find me on gitter.
