### ISSUE TITLE
Wrong way to determine the Bubble hardware and firmware versions

### ISSUE THREAD

**Issue by gui-dos** [dabear/miaomiao-client-swift#18]
The correct way of determining the Bubble hardware and firmware version is not anymore

https://github.com/dabear/miaomiao-client-swift/blob/d6230a07fc978f2bf51bc1891dbb36bdf88daf75/Bluetooth/LibreBluetoothManager%2BBubble.swift#L57-L58
but:
```swift
let hardware = value[value.count-2].description + "." + value[value.count-1].description
let firmware = value[2].description + "." + value[3].description
```
See: https://github.com/NightscoutFoundation/xDrip/commit/60c391f88508114cae0f426ebde4f0a9d24c3669

The Bubble sends a new packet with the "patchInfo" read via NFC (the response type is 0xC1). To extract it you will have to consider the precise firmware version, i.e.:

```swift
let patchInfo = Data(Double(firmware)! < 1.35 ? value[3...8] : value[5...10])

**Comment by dabear** [comment]
Thanks gui-dos! However, this is already solved in another way in the rewrite in https://github.com/dabear/miaomiao-client-swift/pull/17 . I will add these changes you've come up with as comments in the source code if I decide to use the data telegram for figuring out the hardware and firmware versions. Much of the rewrite was inspired by your gitter post at the end of last year btw :)

I don't think patchInfo is necessary in any way though, as you need to have online access to the libreoopweb or glucose.space to use it; and loop should work offline :) 

Thanks for your issue report, really appreciate it! 👍
