### ISSUE TITLE
Apple Watch viable?

### ISSUE THREAD

**Issue by robertherber** [dabear/miaomiao-client-swift#22]
I'm looking for a way to connect my Miaomiao directly to my Apple Watch. I found this repo when looking for an example. Since I have limited experience I'd like to ask you guys if it's viable?

Seems like CoreBluetooth is supported and Blucon already has a similar solution in place https://www.prnewswire.com/news-releases/ambrosia-launches-revolutionary-direct-to-apple-watch-nightrider-blucon-for-continuous-glucose-monitoring-300887904.html

**Comment by dabear** [comment]
No idea. I don't use apple watch :)
