### ISSUE TITLE
XOR with inverted low/high words in usefulFunction()

### ISSUE THREAD

**Issue by gui-dos** [dabear/miaomiao-client-swift#23]
There is a bug in @ivalkou usefulFunction() https://github.com/dabear/miaomiao-client-swift/blob/f78f28a2cdcce576ce4109c8a63085b9943ad6bf/LibreSensor/SensorContents/PreLibre2.swift#L146-L147 which I reported on https://github.com/ivalkou/LibreTools/issues/2

I didn’t get any feedback but without that inversion you won’t be able to activate the BLE streaming of data and decrypt them.

**Comment by dabear** [comment]
Thanks! I'll add that, but this plugin won't use libre2 native bluetooth.

**Comment by dabear** [comment]
https://github.com/dabear/miaomiao-client-swift/commit/fff5b91382f18a9b1a3be3a6a1b7be91841c0179
https://github.com/dabear/miaomiao-client-swift/commit/60b30b6774a6427c101894d26c1b9e3a15b964a1
